# Lychee link checker configuration
# https://lychee.cli.rs/#/configuration

# Base directory for the checker
base = "."

# Maximum number of redirects to follow
max_redirects = 10

# Show progress bars (disabled for CI)
no_progress = true

# Verbose output
verbose = true

# Set of patterns to exclude from checking
exclude = [
    # Skip localhost and local addresses
    "http://localhost.*",
    "http://127.0.0.1.*",
    "https://localhost.*",
    "https://127.0.0.1.*",
    
    # Skip file:// URLs (local files)
    "file://.*",
    
    # Skip mail links
    "mailto:.*",
    
    # Skip common placeholder/example domains
    "http://example.com.*",
    "https://example.com.*",
    
    # Skip anchor links and fragments with specific patterns
    ".*(_anchor|-anchor).*",
    
    # Skip internal documentation anchors that might not exist yet
    ".*#.*"
]

# Exclude patterns from file (if exists)
exclude_file = [".lycheeignore"]

# Accepted status codes (in addition to 200-299)
accept = [
    # Accept all successful status codes
    200,
    # Accept found/redirects
    301, 302, 307, 308,
    # Accept some client errors for external sites
    403,  # Forbidden (some sites block crawlers)
    429,  # Too Many Requests (rate limiting)
]

# User agent string
user_agent = "lychee/hed-web-docs"

# Timeout for requests (in seconds)
timeout = 30

# Number of retry attempts
max_retries = 3

# Headers to send with requests
headers = [
    "Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
]