[general]
# Qtly configuration equivalent to .codeclimate.yml
version = "2"

[checks]
# Argument count check - equivalent to argument-count
[checks.argument-count]
enabled = true
threshold = 4

# Complex logic check - equivalent to complex-logic
[checks.complex-logic]
enabled = true
threshold = 4

# File lines check - equivalent to file-lines
[checks.file-lines]
enabled = true
threshold = 300

# Method complexity check - equivalent to method-complexity
[checks.method-complexity]
enabled = true
threshold = 5

# Method count check - equivalent to method-count
[checks.method-count]
enabled = true
threshold = 20

# Method lines check - equivalent to method-lines
[checks.method-lines]
enabled = true
threshold = 50

# Nested control flow check - equivalent to nested-control-flow
[checks.nested-control-flow]
enabled = true
threshold = 4

# Return statements check - equivalent to return-statements
[checks.return-statements]
enabled = true
threshold = 4

# Similar code detection - equivalent to similar-code
[checks.similar-code]
enabled = true

# Identical code detection - equivalent to identical-code
[checks.identical-code]
enabled = true

[exclude]
# Exclude patterns equivalent to exclude_patterns in .codeclimate.yml
patterns = [
    "config/",
    "db/",
    "dist/",
    "features/",
    "**/node_modules/",
    "script/",
    "**/spec/",
    "**/test/",
    "**/tests/",
    "Tests/",
    "**/vendor/",
    "**/*_test.go",
    "**/*.d.ts",
    "**/*__init__.py",
    "**/*setup.py",
    "**/static/",
    "**/constants/",
    "**/deploy_hed/",
    "**/README*",
    "**/.gitignore",
    "**/LICENSE",
    "**/examples/",
    "**/*.yml",
    "**/*.yaml",
    "**/config_template.py",
    "**/*.txt",
    "**/*.html",
    "**/.coveragerc",
    "**/*.md",
    "**/app_factory.py",
    "**/runserver.py",
    "**/*.rst",
    "**/templates/",
    "**/conf.py",
    "**/deprecated/"
]
