name: CI

on:
  push:
    branches: [ "*"" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install flake8 coverage -r requirements.txt -r docs/requirements.txt

    # Run flake8
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 

    # Run tests with coverage
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        python -m coverage run -m unittest discover -s tests/ -p 'test_*.py'
        python -m coverage run -a -m unittest discover -s services_tests/ -p 'test_*.py'
        python -m coverage xml

    # Upload coverage to qlty
    - name: Upload coverage to qlty
      uses: qltysh/qlty-action/coverage@v2
      with:
        files: coverage.xml
