name: Test service routes externally

# Todo: May want to tweak what branches this runs on
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "*" ]

env:
  BRANCH_NAME: ${{ github.event.pull_request.base.ref || github.ref_name }}


jobs:
  build:
    continue-on-error: true
    env:
      HED_SERVER_URL: "http://127.0.0.1:33004/hed_dev"
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v5

      - name: Make the script files executable
        run: chmod +x deploy/deploy.sh

      - name: Run deploy script (develop)
        run: | 
          cd deploy
          ./deploy.sh "$BRANCH_NAME" dev
          cd ..

      - name: Wait for server to be ready
        run: |
          sleep 10
          curl --retry 10 --retry-delay 5 --retry-connrefused ${{ env.HED_SERVER_URL }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run service tests
        env:
          HED_SERVER_URL_KEY: ${{ env.HED_SERVER_URL }}
        run: python -m unittest discover services_tests

      - name: Show Docker logs on failure
        if: failure()
        run: |
          echo "Displaying Docker logs..."
          docker logs hedtools_dev
