name: Test service routes externally

# Todo: May want to tweak what branches this runs on
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "*" ]

env:
  BRANCH_NAME: ${{ github.event.pull_request.base.ref || github.ref_name }}


jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v5

      - name: Make the script files executable
        run: chmod +x deploy/deploy.sh

      - name: Run deploy script (develop)
        run: | 
          cd deploy
          ./deploy.sh dev "$BRANCH_NAME"
          cd ..

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies(using develop hed-python)
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run service tests
        run: python -m unittest discover services_tests
