name: Test service routes externally

# Todo: May want to tweak what branches this runs on
on:
  push:
    branches: ["*"]

env:
  BRANCH_NAME: ${{ github.event.pull_request.base.ref || github.ref_name }}


jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.10]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Make the script files executable
        run: chmod +x deploy_hed_dev/deploy.sh


      - name: Run deploy script (Stable)
        if: ${{ env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'stable' }}
        run: | 
          cd deploy_hed_dev 
          ./deploy.sh master
          cd ..

      - name: Run deploy script (develop)
        if: ${{ env.BRANCH_NAME != 'stable' && env.BRANCH_NAME != 'master' }}
        run: | 
          cd deploy_hed_dev 
          ./deploy.sh develop
          cd ..

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies(using develop hed-python)
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run service tests
        run: python -m unittest discover services_tests
